---
- hosts: haproxy
  become: true
  roles:
    - role: haproxy
#      haproxy_socket: /var/lib/haproxy/stats
#      haproxy_chroot: /var/lib/haproxy
##      haproxy_user: haproxy
##      haproxy_group: haproxy
#
#      # Frontend settings.
#      haproxy_frontend_name: 'hafrontend'
#      haproxy_frontend_bind_address: '*'
#      haproxy_frontend_port: 80
#      haproxy_frontend_mode: 'http'
#
#      # Backend settings.
#      haproxy_backend_name: 'habackend'
#      haproxy_backend_mode: 'http'
#      haproxy_backend_balance_method: 'roundrobin'
#      haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'

#      # List of backend servers.
#      haproxy_backend_servers: #[]
#        - name: app1
#          address: 192.168.201.11:5000
#        - name: app2
#          address: 192.168.201.12:5000

- hosts: mongodb
  become: yes
  name: Include mongodb
  roles:
    - role: mongo
      vars:
        # the mongo version to use when installing via yum, ignored when installing from rpm files
        mongo_version: 3.6

        # The name of the mongo process
        mongo_process_name: mongod

        # The location of the database files
        mongo_db_dir: /data/db

        # The location of the configuration file
        mongo_conf_file: "/etc/mongod.conf"

        # The location of the pid file
        mongo_pid_file: "/var/run/mongodb/mongod.pid"

        # The location of the log file
        mongo_log_path: "/var/log/mongodb/mongod.log"

        # Mongo port
        mongo_port: 27017

        # Mongo logging properties
        mongo_log_append: false
        mongo_log_rotate: rename
        mongo_log_verbosity: 0

        # Determines whether the process should be forked
        mongo_fork_process: true

        mongo_cluster_role: shardsvr

        mongo_authorization: disabled

        # Whether to perform selinux-specific configuration, default is true
        selinux_enabled: true

        # ssl properties:
        mongo_ssl_enabled: false
        # the following are required if mongo_ssl_enabled is true:
        #mongo_ssl_mode:
        #mongo_ssl_pem_key_file:
        #mongo_ssl_pem_key_password: (optional)
        #mongo_ssl_ca_file:
        #mongo_ssl_allow_invalid_certificates:
        #mongo_ssl_allow_invalid_hostnames:


- hosts: elasticsearch
  become: yes
  name: Include elasticsearch master
  roles:
    - role: elastic.elasticsearch
      vars:
        es_instance_name: "node1"
        es_config:
          node.name: "node1"
          cluster.name: "custom-cluster"
          discovery.zen.ping.unicast.hosts: "localhost:9200"
          http.port: 9200
          transport.tcp.port: 9200
          node.data: false
          node.master: true
          bootstrap.memory_lock: true
        es_version_lock: false
        es_heap_size: 1g
        es_api_port: 9200
        es_xpack_features: []

- hosts: apps
  become: yes
  roles:
    - role: data-engineering-app
#  environment:
#    ELASTICSEARCH_URL: http://192.168.201.14:9200
#    MONGODB_URI: mongodb://192.168.201.13:27017